"""
05_math_doc.py
--------------
Assemble the work-log document: every quantity in the manuscript, the formula that
produced it, the file and script that produced it, and the raw source it traces back to.

Writes HTML because the destination is a Google Doc, and Drive converts text/html
cleanly while it flattens Markdown. Reads only the CSVs in output/, so it cannot
disagree with the analysis.
"""
from __future__ import annotations
import argparse, html, os
import pandas as pd

CSS = """
body{font-family:Georgia,'Times New Roman',serif;font-size:11pt;line-height:1.45;color:#111}
h1{font-size:19pt;margin:0 0 4pt}
h2{font-size:14pt;margin:22pt 0 6pt;border-bottom:1px solid #bbb;padding-bottom:3pt}
h3{font-size:11.5pt;margin:14pt 0 4pt;font-style:italic;font-weight:normal;color:#333}
p{margin:6pt 0}
table{border-collapse:collapse;margin:8pt 0;font-size:9.5pt;font-family:Arial,Helvetica,sans-serif}
th,td{border:1px solid #ccc;padding:3pt 7pt;text-align:right}
th{background:#f0f0f0;text-align:center;font-weight:bold}
td:first-child,th:first-child{text-align:left}
code,.mono{font-family:'Courier New',monospace;font-size:9.5pt;background:#f6f6f6;padding:0 3px}
.formula{font-family:'Courier New',monospace;font-size:10pt;background:#f6f6f6;
  border-left:3px solid #999;padding:7pt 10pt;margin:8pt 0;white-space:pre-wrap}
.note{color:#555;font-size:10pt;margin:5pt 0 5pt 12pt}
.src{color:#666;font-size:9pt;font-family:Arial,Helvetica,sans-serif;margin:3pt 0 12pt}
.flag{background:#fff4e5;border-left:3px solid #d55e00;padding:7pt 10pt;margin:8pt 0}
"""


def tbl(df, index_name=None, floatfmt='{:,.1f}', sig=None):
    d = df.copy()
    if index_name:
        d.index.name = index_name
    out = ['<table><tr><th>' + html.escape(str(d.index.name or '')) + '</th>' +
           ''.join(f'<th>{html.escape(str(c))}</th>' for c in d.columns) + '</tr>']
    for i, r in d.iterrows():
        cells = []
        for col, v in r.items():
            if isinstance(v, float):
                if pd.isna(v):
                    cells.append('')
                elif str(col) in ('n', 'schools', 'matched', 'leas', 'leas_with_valid_id',
                                  'vent_answered', 'n_hi', 'n_lo'):
                    cells.append(f'{v:,.0f}')
                elif sig:
                    cells.append(f'{v:.{sig}g}')
                else:
                    cells.append(floatfmt.format(v))
            else:
                cells.append(html.escape(str(v)) if pd.notna(v) else '')
        out.append('<tr><td>' + html.escape(str(i)) + '</td>' +
                   ''.join(f'<td>{c}</td>' for c in cells) + '</tr>')
    out.append('</table>')
    return '\n'.join(out)


def src(text):
    return f'<p class="src">Source: {text}</p>'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='output')
    ap.add_argument('--file', default='output/math_workbook.html')
    a = ap.parse_args()
    R = lambda n: pd.read_csv(os.path.join(a.out, n), index_col=0)   # noqa: E731

    H = [f'<style>{CSS}</style>',
         '<h1>ESSER ventilation and industrial exposure: complete computation record</h1>',
         '<p>Every quantity that appears in the manuscript, with the formula that produced '
         'it, the script and output file it comes from, and the federal source file it '
         'traces back to. Nothing in the paper should be here without a line in this '
         'document, and nothing here is typed by hand: this file is generated by '
         '<code>src/05_math_doc.py</code> from the CSVs that <code>src/03_analysis.py</code> '
         'writes.</p>',
         '<p>Run order: <code>01_build_exposure.py</code> &rarr; '
         '<code>02_build_dataset.py</code> &rarr; <code>03_analysis.py</code> &rarr; '
         '<code>04_figures.py</code>. <code>00_audit_legacy.py</code> reproduces the '
         'earlier pipeline and quantifies what changed.</p>']

    # ---------------------------------------------------------------- provenance
    H += ['<h2>0. Source files</h2>',
          '<table><tr><th>File</th><th>Publisher</th><th>Vintage</th><th>Rows</th>'
          '<th>Used for</th></tr>'
          '<tr><td>EDGE_GEOCODE_PUBLICSCH_2425.TXT</td><td>NCES</td><td>2024-25</td>'
          '<td>102,178</td><td>school coordinates, LEAID, county FIPS</td></tr>'
          '<tr><td>epa_tri_national.csv</td><td>EPA TRI</td><td>RY2024</td>'
          '<td>77,295</td><td>facility coordinates and air releases</td></tr>'
          '<tr><td>esf_hvac_spending.xlsx (crossact)</td><td>ED OESE</td><td>FY2023 APR</td>'
          '<td>18,804</td><td>district ventilation / cleaning / PPE flags</td></tr>'
          '<tr><td>esf_hvac_spending.xlsx (prime)</td><td>ED OESE</td><td>FY2023 APR</td>'
          '<td>52</td><td>state allocation, expenditure, remaining</td></tr>'
          '<tr><td>ACSDT5Y2024.B19013-Data.csv</td><td>Census ACS</td><td>2024 5-yr</td>'
          '<td>3,222</td><td>county median household income</td></tr>'
          '<tr><td>ACSDT5Y2024.B03002-Data.csv</td><td>Census ACS</td><td>2024 5-yr</td>'
          '<td>3,222</td><td>county race by Hispanic origin</td></tr></table>']

    # ---------------------------------------------------------------- exposure
    H += ['<h2>1. Exposure index</h2>',
          '<h3>1.1 Facility aggregation</h3>',
          '<p>The TRI Basic Data File is chemical-release-form level. 77,295 rows describe '
          '21,482 facilities; the largest single facility files 218 forms. Aggregate first:</p>',
          '<pre class="formula">m_f = SUM over that facility\'s forms of '
          '( "5.1 - FUGITIVE AIR" + "5.2 - STACK AIR" )   [pounds, 2024]</pre>',
          '<p class="note">Fugitive plus stack air is the airborne fraction. Total releases '
          '(column 107) includes water, land and underground injection, which do not reach a '
          'school through its ventilation system. Negative values, which EPA uses for '
          'data-entry corrections, are clipped to zero.</p>',
          src('<code>src/01_build_exposure.py</code>, function <code>aggregate_tri</code>. '
              'Writes <code>data/derived/tri_facilities_2024.csv</code>.'),

          '<h3>1.2 The index</h3>',
          '<pre class="formula">E_s = SUM over facilities f with d_sf &lt;= 50 km of\n'
          '        m_f / max(d_sf, 0.1 km)^2\n\n'
          'd_sf   great-circle chord distance, cKDTree on radian coordinates,\n'
          '       multiplied by 6371 km. At 50 km the chord understates the arc\n'
          '       by under 0.1 percent.\n'
          'k      500 nearest facilities retained. The cap never binds: the median\n'
          '       school has 50 TRI facilities within 50 km.\n'
          '0.1 km distance floor. A school is a building, not a point, and no school\n'
          '       sits inside a fenceline. Caps one facility\'s contribution at m_f/0.01.</pre>',
          '<h3>1.3 Normalisation</h3>',
          '<pre class="formula">EXPOSURE_s = min( 100 , 100 * E_s / Q99(E) )</pre>',
          '<p class="note">Anchored on the 99th percentile so the published tier cutpoints '
          '(0.5 / 10 / 25 / 50 / 75) remain comparable. The scale is relative by '
          'construction: a school at 100 is in the top percentile of American schools, not '
          'above any health threshold. Because the top percentile is clipped to a single '
          'value, the percentile-band analysis in section 4 ranks on the unnormalised '
          '<code>E_air_raw_lbs_per_km2</code> instead.</p>',

          '<h3>1.4 The four specifications, and what separates them</h3>',
          '<table><tr><th>Column</th><th>Point cloud</th><th>Denominator</th><th>k</th>'
          '<th>Weight</th></tr>'
          '<tr><td>E_forms</td><td>chemical forms (77,295)</td><td>d&sup2; + 1e-5 (rad&sup2;)</td>'
          '<td>50</td><td>none</td></tr>'
          '<tr><td>E_fac</td><td>facilities (21,482)</td><td>d&sup2; + 1e-5 (rad&sup2;)</td>'
          '<td>50</td><td>none</td></tr>'
          '<tr><td>E_isq</td><td>facilities</td><td>max(d, 0.1 km)&sup2; in km&sup2;</td>'
          '<td>500</td><td>none</td></tr>'
          '<tr><td>E_air (canonical)</td><td>facilities</td>'
          '<td>max(d, 0.1 km)&sup2; in km&sup2;</td><td>500</td><td>air releases, lbs</td></tr>'
          '</table>',
          '<p><code>E_forms</code> reproduces the previously published index at Pearson '
          'r = 0.99998 and exists only so the comparison is verifiable.</p>',
          tbl(R('tier_counts_by_variant.csv'), 'Tier', '{:,.0f}'),
          '<div class="flag"><b>Why this matters.</b> Identical cutpoints, four '
          'specifications, and the count of "Critical" schools moves from 28,200 to 1,052. '
          'Aggregating to facilities alone changes the tier of 56.8 percent of schools; '
          'replacing the softening constant with a physical floor changes 94.4 percent. '
          'The legacy denominator added 1e-5 to a squared <i>radian</i> distance: a facility '
          '20 km away has d&sup2; = 9.9e-6, smaller than the constant, so across the full '
          '0 to 50 km range the weight ratio was 7.2 : 1 where a true inverse square gives '
          '10,000 : 1.</div>',
          src('<code>src/00_audit_legacy.py</code> reproduces both the index and this table.')]

    # ---------------------------------------------------------------- linkage
    cov = R('coverage_by_state.csv')
    H += ['<h2>2. Linkage and missingness</h2>',
          '<h3>2.1 Identifier validation</h3>',
          '<pre class="formula">LEAID = zfill(ncesNumber, 7)\n'
          'keep LEAID only if LEAID[0:2] == FIPS(stateCode), else treat as unlinkable</pre>',
          '<p class="note">Without the prefix check, New Hampshire\'s six-digit local code '
          '502960 pads to 0502960, a real Arkansas LEAID, merging New Hampshire\'s Benton '
          'onto Arkansas\'s Benton. Duplicate identifiers fall from 2,416 rows to 16, and '
          'the school file stops inflating from 102,178 to 102,866 rows (688 duplicate rows across 602 schools). 869 identifiers '
          'are rejected.</p>',
          '<h3>2.2 The outcome coding rule</h3>',
          '<pre class="formula">HAS_VENT = 1   if isEsserAUsedFundsVentilation is True\n'
          '           0   if False\n'
          '           .   otherwise  (blank means the district did not answer)</pre>',
          '<p class="note">Blank is missing, not zero. Across the linkable states, reading '
          'blanks as zeros moves the national rate from 57.7 to 53.9 percent; at community '
          'scale it moves Bronx County from 44.8 to 5.5 percent.</p>',
          '<h3>2.3 Coverage by state, lowest 14</h3>',
          tbl(cov.sort_values('pct_matched')[['schools', 'matched', 'pct_matched',
                                              'leas', 'leas_with_valid_id', 'pct_id',
                                              'vent_answered', 'lea_funded_pct']].head(14),
              'State', '{:,.1f}'),
          '<div class="flag"><b>Arizona, Connecticut, Texas and Washington answered the '
          'ventilation question for all 2,297 of their districts and left the NCES '
          'identifier blank on every row.</b> 16,023 schools are therefore unlinkable. A '
          'pipeline that infers reporting status from a failed join reads this as '
          '"did not report", which is false. Their measured district-level rates are '
          'Arizona 41.4, Connecticut 41.0, Texas 23.4, Washington 52.3 percent.</div>',
          '<p>Oklahoma is the opposite case: 540 agencies, 540 valid identifiers, 540 '
          'answers, all False. It is retained. A rule that recodes states below a 2 percent '
          'funded rate to missing deletes exactly this observation and biases the national '
          'rate upward.</p>',
          src('<code>src/02_build_dataset.py</code>; <code>output/coverage_by_state.csv</code>.')]

    # ---------------------------------------------------------------- results
    H += ['<h2>3. Sample and headline rates</h2>',
          '<pre class="formula">analytic sample = schools in linkable states\n'
          '   AND HAS_VENT observed  AND exposure observed\n'
          '   AND county income observed  AND county race observed\n'
          ' = 80,308 schools across 48 states</pre>',
          '<p>Recorded ventilation funding: <b>57.7 percent</b> (Wilson 95 percent CI 57.4 '
          'to 58.1). Wilson rather than Wald because several state and tail cells sit at or '
          'near 0 and 100 percent, where the normal approximation leaves the unit interval.</p>',
          '<pre class="formula">Wilson interval, k successes in n:\n'
          '  centre = (p + z^2/(2n)) / (1 + z^2/n)\n'
          '  half   = z*sqrt( p(1-p)/n + z^2/(4n^2) ) / (1 + z^2/n)</pre>',
          tbl(R('grant_categories.csv'), 'Grant category', '{:,.1f}')]

    H += ['<h2>4. Exposure and funding</h2>',
          '<h3>4.1 By percentile band of the unnormalised index</h3>',
          tbl(R('funded_by_exposure_percentile_band.csv'), 'Band', '{:,.1f}'),
          '<p>The rise from 54.2 to 70.0 percent across the first five bands, then the fall '
          'to 43.2 percent among the 81 schools above the 99.9th percentile, is the '
          'manuscript\'s central result. A tail result carried by one state\'s reporting '
          'practice would be a different finding, so here is where those 81 schools are: '
          + ', '.join(f'{s} {int(n)}' for s, n in
                      R('top_band_states.csv').schools.items()) + '.</p>',
          '<h3>4.2 The same cut under all four exposure specifications</h3>',
          tbl(R('sensitivity_exposure.csv').reset_index().pivot(
              index='quintile', columns='variant', values='funded_pct'), 'Quintile'),
          '<h3>4.3 By the legacy fixed tiers, canonical index</h3>',
          tbl(R('funded_by_exposure_tier.csv'), 'Tier', '{:,.1f}')]

    H += ['<h2>5. Models</h2>',
          '<pre class="formula">A:  HAS_VENT ~ exp10\n'
          'B:  HAS_VENT ~ exp10 + inc10k + poc10\n'
          'C:  HAS_VENT ~ exp10 + inc10k + poc10 + C(STATE)     [primary]\n\n'
          'exp10  = EXPOSURE / 10          inc10k = county median income / 10,000\n'
          'poc10  = percent people of color / 10\n\n'
          'aOR    = exp(b);  95% CI = exp(b +/- 1.96*SE)\n'
          'C-stat = Mann-Whitney form of the ROC area, midranks for ties</pre>',
          tbl(R('models.csv'), 'Model', sig=3),
          '<p class="note">Models S and B&#39; exist so that "does the state predict better '
          'than the school\'s own environment" is answered rather than asserted. A and B are '
          'fitted on the full analytic sample and C on the mixed-state subset, so their '
          'C-statistics are not comparable; S and B&#39; are both fitted on C\'s 75,961 '
          'schools. State indicators alone give 0.701, the three covariates alone 0.657, '
          'together 0.733.</p>',
          '<p class="note">Model C is estimated on the 44 states with within-state variation. '
          'Oklahoma, Hawaii, Maryland and Puerto Rico drop by perfect separation, which is '
          'reported rather than worked around. Adding county race attenuates the exposure '
          'aOR from 1.083 to 1.043. McFadden\'s pseudo-R&sup2; is an index, not variance '
          'explained.</p>',
          '<h3>5.1 The tail specification</h3>',
          '<pre class="formula">HAS_VENT ~ t95 + t99 + t999 + inc10k + poc10 + C(STATE)\n\n'
          't95  = 1 if percentile in (95, 99]        of E_air_raw\n'
          't99  = 1 if percentile in (99, 99.9]\n'
          't999 = 1 if percentile &gt; 99.9\n'
          'reference = everything at or below the 95th percentile</pre>',
          tbl(R('tail_odds.csv'), 'Band', sig=3),
          '<p class="note">Quintile and tier contrasts average over 16,000 schools each and '
          'cannot detect a phenomenon confined to a few dozen. A quadratic in log10 exposure '
          'is fitted as a check on smooth curvature and is not distinguishable from zero '
          '(b = 0.004, p = 0.37), so the pattern is a rising association with a tail break, '
          'not an inverted U.</p>',
          '<h3>5.2 Adjusted odds by exposure quintile</h3>',
          tbl(R('exposure_quintile_odds.csv'), 'Quintile', sig=3)]

    H += ['<h2>6. Community composition</h2>',
          '<h3>6.1 By county percent people of color</h3>',
          '<pre class="formula">pct_poc = (1 - B03002_003E / B03002_001E) * 100\n'
          '  B03002_001E  county total\n'
          '  B03002_003E  not Hispanic or Latino, White alone</pre>',
          '<p class="note">B03002 rather than B02001: Hispanic origin is an ethnicity in the '
          'Census framework, and B02001 counts many Hispanic respondents as White alone, '
          'which would understate the people-of-color share heavily in the Southwest and '
          'south Florida.</p>',
          tbl(R('funded_by_pct_poc_quintile.csv'), 'Quintile', '{:,.1f}'),
          '<h3>6.2 By county median household income</h3>',
          tbl(R('funded_by_median_income_quintile.csv'), 'Quintile', '{:,.1f}'),
          '<p class="note">Both covariates are county-level and therefore ecological. County '
          'income is entangled with urbanicity to the point where its negative coefficient '
          'should not be read as a statement about wealth and need.</p>']

    H += ['<h2>7. Within-state gradient</h2>',
          '<pre class="formula">gap_state = funded%( state\'s own top exposure quintile )\n'
          '          - funded%( state\'s own bottom exposure quintile )\n\n'
          'Within-state quintiles, so each state is compared only against itself.\n'
          'States with fewer than 50 schools in either band are omitted.</pre>',
          tbl(R('within_state_gap.csv'), 'State', '{:,.1f}')]

    cs = R('case_studies.csv')
    H += ['<h2>8. Regional cases</h2>',
          tbl(cs, 'Case', '{:,.1f}'),
          '<div class="flag"><b>The last two columns are the test.</b> Where school-level '
          'coverage is high the two codings agree and the finding is real: Albuquerque links '
          '91.8 percent of its schools and reads 2.1 percent funded either way, and '
          'Albuquerque Public Schools reported False in its own federal filing. Where '
          'coverage is low they diverge: Bronx County links 12.3 percent, reads 44.8 percent '
          'over linked schools and 5.5 percent under blank-as-zero, and the district of '
          'record for New York City public schools (NYC Chancellor\'s Office, LEAID 3620580, '
          '827,736 students) reported True. Houston ISD also reported True; Texas is '
          'unlinkable, not silent. Gary Community School Corporation reported True and '
          'submitted no identifier, so its schools are absent from the Lake County '
          'figure entirely.</div>']

    fu = R('esser_funding_position.csv')
    H += ['<h2>9. Funding position and the cliff</h2>',
          tbl(fu, 'Fund', '{:,.2f}'),
          '<p>Position as of the FY2023 APR, 30 September 2023, summed across 52 state and '
          'territory grantees. Obligation deadlines were 30 September 2022, 2023 and 2024 '
          'respectively (Tydings carryover, 20 U.S.C. 1225(b)), with liquidation due 120 '
          'days after. ARP ESSER was 53.1 percent unspent twelve months before its '
          'obligation deadline.</p>',
          '<p class="note">Allocation figures are pre-filled by the Department from its G5 '
          'system; expenditure figures are grantee-reported on either a cash or accrual '
          'basis, which the Department\'s own data notes flag as inconsistent across '
          'grantees though consistent within a grantee over time.</p>']

    H += ['<h2>10. What is not modelled</h2>',
          '<p>Each district makes one funding decision covering all of its schools, so '
          'school-level observations are not independent within districts and the reported '
          'standard errors are too small. State fixed effects absorb part of this. A '
          'district-clustered specification is the obvious next robustness check and is not '
          'run here. The outcome is a binary flag, not a dollar amount: a district that '
          'spent forty thousand dollars on filters and one that spent twelve million on air '
          'handlers are recorded identically. Facilities that report to TRI are a subset of '
          'emitters, bounded by reporting thresholds and covered sectors, so a school beside '
          'a large non-reporting source scores as unexposed. The design is cross-sectional '
          'and every estimate is associational. The tail result rests on 81 schools with a '
          'Wilson interval from 33.0 to 54.1 percent, and should be read as a well-supported '
          'hypothesis rather than a settled quantity.</p>']

    open(a.file, 'w').write('\n'.join(H))
    print(f'wrote {a.file}')


if __name__ == '__main__':
    main()
